#!/bin/bash

if [[ "$OSTYPE" == "darwin"* ]]; then
  if ! command -v say &> /dev/null
  then
      echo "say could not be found, make sure it is installed and try again."
      exit
  fi
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
  if ! command -v espeak &> /dev/null
  then
      echo "espeak could not be found, make sure it is installed and try again."
      exit
  fi
fi


if [[ -z $1 || -z $2 ]]; then
	echo " usage: ./check \"<url>\" \"<message>\" [interval]"
else 
	clear;


chmod +x .


sleep 0.2

./banner.sh

sleep 0.3


while [ : ]
do
    echo -ne "\n Check for changes" '|\r'
    sleep 0.4
    echo -ne "cHeck for changes" '/\r'
    sleep 0.4
    echo -ne "chEck for changes" '一\r'
    sleep 0.4
    echo -ne "cheCk for changes" '\\ \r'
    sleep 0.4
    echo -ne "checK for changes" '|\r'
    sleep 0.4
    echo -ne "check For changes" '$\r'
    sleep 0.4

    echo -ne "check fOr changes" '|\r'
    sleep 0.3
    echo -ne "cHeck foR changes" '/\r'
    sleep 0.3
    echo -ne "check for Changes" '一\r'
    sleep 0.3
    echo -ne "check for cHanges" '\\ \r'
    sleep 0.3
    echo -ne "check for chAnges" '|\r'
    sleep 0.3
    echo -ne "check For chaNges" '$\r'
    sleep 0.3
    
    echo -ne "check for chanGes" '|\r'
    sleep 0.3
    echo -ne "check for changEs" '/\r'
    sleep 0.3
    echo -ne "check for ChangeS" '一\r\n'
    sleep 0.3
    break;
done
	

	interval=10
	if [ ! -z $3 ]; then
		interval=$3
	fi
	
	if [ -f /tmp/previous.html ]; then
		rm /tmp/previous.html
	fi

	while :
	do
		current=`curl $1 2> /dev/null`;

		if [ ! -f /tmp/previous.html ]; then
			echo -e "\n Writing in /tmp/previous.html";
       			mkdir -p "`dirname \"/tmp/previous.html\"`" 2>/dev/null
			echo "$current" >> "/tmp/previous.html"
		fi

		previous="`cat /tmp/previous.html`";

		current_count=`echo -e "$current" | wc -l`
		previous_count=`echo -e "$previous" | wc -l`
		
		echo -e "\t$current_count vs. $previous_count" ;

		if [ "$previous_count" = "$current_count" ]; then
			echo -e "\n****************************************\n$(date)\nNothing New...\n****************************************\n"
			sleep $interval
			clear;

			./banner.sh
			echo -e "\n"
		else
			echo -e "\n****************************************\n$(date)\nNew Content!\n****************************************\n"

			if [[ "$OSTYPE" == "darwin"* ]]; then
        say $2;

      elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
        espeak $2;
      fi
			break;
		fi
	done
fi

rm /tmp/previous.html;
